import turtle                           # Tell Python we want to work with the turtle
turtle.setup (width=600, height=600)    # Set the size of the window

tina = turtle.Turtle()                  # Create a turtle named tina

tina.shape('turtle')                    # Set the shape of the turtle to a turtle
tina.speed(1)                           # Make the turtle move as fast, but not 
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.teleport(1)
tina.forward(155)
tina.circle(175)
tina.forward(1000)


turtle.exitonclick()                    # Close the window when we click on it